import "~/styles/globals.css";

import { type Metadata } from "next";
import Sidebar from "~/components/sidebar";
import { Template } from "~/components/template";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" >
    <Template>      
    <Sidebar/>
    {children}
    </Template>
    </html>
  );
}
